### ISSUE TITLE
[fetcheus] go-velocity does not work

### ISSUE THREAD

**Issue by MiyabiTane** [jsk-ros-pkg/jsk_robot#1154]
```
(send *ri* :go-velocity 0.1 0 0.5)
[ERROR] [1571647540.324682228]: Setting velocity in y-axis is not valid for non-holonomic robot
nil
```

cc @Affonso-Gui  @YutoUchimi

**Comment by knorth55** [comment]
FYI: PR2 is holonomic robot and fetch is non-holonomic robot.

**Comment by pazeshun** [comment]
I understand what is happening.
@MiyabiTane I'll fix the critical issue, but please be careful when using `:go-velocity` even after it is fixed, because this method doesn't seem used in real robot.
Sorry for your trouble...

The following source code is for catching a case in which second argument (velocity in y direction) **is not 0**:
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/fetcheus/fetch-interface.l#L212-L215
This is because fetch cannot move in y direction (non-holonomic).
However, the above code is wrong as it works when second argument **is 0** (`unless (not (zerop y)`).
